using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DD.CBU.Compute.Api.Contracts.Vip
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34014
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://oec.api.opsource.net/schemas/vip")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://oec.api.opsource.net/schemas/vip", IsNullable = false)]
    public partial class NewProbe
    {

        private string nameField;

        private string typeField;

        private string probeIntervalSecondsField;

        private string errorCountBeforeServerFailField;

        private string successCountBeforeServerEnableField;

        private string failedProbeIntervalSecondsField;

        private string maxReplyWaitSecondsField;

        private string requestMethodField;

        private string portField;

        private string requestUrlField;

        private string matchContentField;

        private NewProbeStatusCodeRange[] statusCodeRangeField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string probeIntervalSeconds
        {
            get
            {
                return this.probeIntervalSecondsField;
            }
            set
            {
                this.probeIntervalSecondsField = value;
            }
        }

        /// <remarks/>
        public string errorCountBeforeServerFail
        {
            get
            {
                return this.errorCountBeforeServerFailField;
            }
            set
            {
                this.errorCountBeforeServerFailField = value;
            }
        }

        /// <remarks/>
        public string successCountBeforeServerEnable
        {
            get
            {
                return this.successCountBeforeServerEnableField;
            }
            set
            {
                this.successCountBeforeServerEnableField = value;
            }
        }

        /// <remarks/>
        public string failedProbeIntervalSeconds
        {
            get
            {
                return this.failedProbeIntervalSecondsField;
            }
            set
            {
                this.failedProbeIntervalSecondsField = value;
            }
        }

        /// <remarks/>
        public string maxReplyWaitSeconds
        {
            get
            {
                return this.maxReplyWaitSecondsField;
            }
            set
            {
                this.maxReplyWaitSecondsField = value;
            }
        }

        /// <remarks/>
        public string requestMethod
        {
            get
            {
                return this.requestMethodField;
            }
            set
            {
                this.requestMethodField = value;
            }
        }

        /// <remarks/>
        public string port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        public string requestUrl
        {
            get
            {
                return this.requestUrlField;
            }
            set
            {
                this.requestUrlField = value;
            }
        }

        /// <remarks/>
        public string matchContent
        {
            get
            {
                return this.matchContentField;
            }
            set
            {
                this.matchContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusCodeRange")]
        public NewProbeStatusCodeRange[] statusCodeRange
        {
            get
            {
                return this.statusCodeRangeField;
            }
            set
            {
                this.statusCodeRangeField = value;
            }
        }
    }
}
