using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DD.CBU.Compute.Api.Contracts.Vip
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34014
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://oec.api.opsource.net/schemas/vip")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://oec.api.opsource.net/schemas/vip", IsNullable = false)]
    public partial class NewVip
    {

        private string nameField;

        private string ipAddressField;

        private string portField;

        private string protocolField;

        private string vipTargetTypeField;

        private string vipTargetIdField;

        private string replyToIcmpField;

        private string inServiceField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string ipAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }

        /// <remarks/>
        public string port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        public string protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        public string vipTargetType
        {
            get
            {
                return this.vipTargetTypeField;
            }
            set
            {
                this.vipTargetTypeField = value;
            }
        }

        /// <remarks/>
        public string vipTargetId
        {
            get
            {
                return this.vipTargetIdField;
            }
            set
            {
                this.vipTargetIdField = value;
            }
        }

        /// <remarks/>
        public string replyToIcmp
        {
            get
            {
                return this.replyToIcmpField;
            }
            set
            {
                this.replyToIcmpField = value;
            }
        }

        /// <remarks/>
        public string inService
        {
            get
            {
                return this.inServiceField;
            }
            set
            {
                this.inServiceField = value;
            }
        }
    }



}
