//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace DD.CBU.Compute.Api.Contracts.Network20
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class RulePlacementType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RulePositionType position;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relativeToRule;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public enum RulePositionType
    {

        /// <remarks/>
        BEFORE,

        /// <remarks/>
        AFTER,

        /// <remarks/>
        FIRST,

        /// <remarks/>
        LAST,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class IpAndPortType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ip", typeof(IpAndPortTypeIP))]
        [System.Xml.Serialization.XmlElementAttribute("ipAddressListId", typeof(string))]
        public object Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port", typeof(PortRangeType))]
        [System.Xml.Serialization.XmlElementAttribute("portListId", typeof(string))]
        public object Item1;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class IpAndPortTypeIP
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int prefixSize;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prefixSizeSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class PortRangeType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort begin;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort end;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class IpAndPortFilterType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ip", typeof(IpAndPortFilterTypeIP))]
        [System.Xml.Serialization.XmlElementAttribute("ipAddressList", typeof(IpAddressListSummaryType))]
        public object ip;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port", typeof(PortRangeType))]
        [System.Xml.Serialization.XmlElementAttribute("portList", typeof(PortListSummaryType))]
        public object port;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class IpAndPortFilterTypeIP
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int prefixSize;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prefixSizeSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class IcmpPropertiesType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int type;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("firewallRule", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class FirewallRuleType
    {

        /// <remarks/>
        public string networkDomainId;

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string action;

        /// <remarks/>
        public string ipVersion;

        /// <remarks/>
        public string protocol;

        /// <remarks/>
        public IcmpPropertiesType icmpProperties;

        /// <remarks/>
        public IpAndPortFilterType source;

        /// <remarks/>
        public IpAndPortFilterType destination;

        /// <remarks/>
        public bool enabled;

        /// <remarks/>
        public string state;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datacenterId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ruleType;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class firewallRules
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("firewallRule")]
        public FirewallRuleType[] firewallRule;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageNumber;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageCountSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int totalCount;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageSize;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("createFirewallRule", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class CreateFirewallRuleType
    {

        /// <remarks/>
        public string networkDomainId;

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string action;

        /// <remarks/>
        public string ipVersion;

        /// <remarks/>
        public string protocol;

        /// <remarks/>
        public IpAndPortType source;

        /// <remarks/>
        public IpAndPortType destination;

        /// <remarks/>
        public bool enabled;

        /// <remarks/>
        public RulePlacementType placement;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("deleteFirewallRule", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class DeleteFirewallRuleType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("editFirewallRule", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class EditFirewallRuleType
    {
        /// <remarks/>
        public string action;

        /// <remarks/>
        public string protocol;

        /// <remarks/>
        public IpAndPortFilterType source;

        /// <remarks/>
        public IpAndPortFilterType destination;

        /// <remarks/>
        public bool enabled;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified;

        /// <remarks/>
        public RulePlacementType placement;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
    }

}
