//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace DD.CBU.Compute.Api.Contracts.Network20
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class VlanIdOrPrivateIpType
    {

        private string itemField;

        private PrivateIpv4OrVlanIdChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("privateIpv4", typeof (string), Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("vlanId", typeof (string), Order = 1)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public PrivateIpv4OrVlanIdChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class NewNicType
    {

        private string itemField;

        private string networkAdapterField;

        private PrivateIpv4OrVlanIdChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("privateIpv4", typeof (string))]
        [System.Xml.Serialization.XmlElementAttribute("vlanId", typeof (string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public PrivateIpv4OrVlanIdChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        public string networkAdapter
        {
            get { return this.networkAdapterField; }
            set { this.networkAdapterField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types", IncludeInSchema = false)]
    public enum PrivateIpv4OrVlanIdChoiceType
    {

        /// <remarks/>
        privateIpv4,

        /// <remarks/>
        vlanId,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class NicType
    {

        private string idField;

        private string privateIpv4Field;

        private string ipv6Field;

        private string vlanIdField;

        private string vlanNameField;

        private string macAddressField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string privateIpv4
        {
            get { return this.privateIpv4Field; }
            set { this.privateIpv4Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ipv6
        {
            get { return this.ipv6Field; }
            set { this.ipv6Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vlanId
        {
            get { return this.vlanIdField; }
            set { this.vlanIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vlanName
        {
            get { return this.vlanNameField; }
            set { this.vlanNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string macAddress
        {
            get { return this.macAddressField; }
            set { this.macAddressField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("server", Namespace = "urn:didata.com:api:cloud:types",
        IsNullable = false)]
    public partial class ServerType
    {

        private string nameField;

        private string descriptionField;

        private OperatingSystemType operatingSystemField;

        private CpuType cpuField;

        private uint memoryGbField;

        private ServerTypeDisk[] diskField;

        private object itemField;

        private ServerTypeBackup backupField;

        private ServerTypeMonitoring monitoringField;

        private string[] softwareLabelField;

        private string sourceImageIdField;

        private System.DateTime createTimeField;

        private bool deployedField;

        private bool startedField;

        private string stateField;

        private ProgressType progressField;

        private VmwareToolsType vmwareToolsField;

        private VirtualHardwareType virtualHardwareField;

        private string idField;

        private string datacenterIdField;

        private drsEligible drsEligibleField;

	    private consistencyGroup consistencyGroupField;

		/// <remarks/>
		public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        public OperatingSystemType operatingSystem
        {
            get { return this.operatingSystemField; }
            set { this.operatingSystemField = value; }
        }

        /// <remarks/>
        public CpuType cpu
        {
            get { return this.cpuField; }
            set { this.cpuField = value; }
        }

        /// <remarks/>
        public uint memoryGb
        {
            get { return this.memoryGbField; }
            set { this.memoryGbField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("disk")]
        public ServerTypeDisk[] disk
        {
            get { return this.diskField; }
            set { this.diskField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("networkInfo", typeof (ServerTypeNetworkInfo))]
        [System.Xml.Serialization.XmlElementAttribute("nic", typeof (ServerTypeNic))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        public ServerTypeBackup backup
        {
            get { return this.backupField; }
            set { this.backupField = value; }
        }

        /// <remarks/>
        public ServerTypeMonitoring monitoring
        {
            get { return this.monitoringField; }
            set { this.monitoringField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("softwareLabel")]
        public string[] softwareLabel
        {
            get { return this.softwareLabelField; }
            set { this.softwareLabelField = value; }
        }

        /// <remarks/>
        public string sourceImageId
        {
            get { return this.sourceImageIdField; }
            set { this.sourceImageIdField = value; }
        }

        /// <remarks/>
        public System.DateTime createTime
        {
            get { return this.createTimeField; }
            set { this.createTimeField = value; }
        }

        /// <remarks/>
        public bool deployed
        {
            get { return this.deployedField; }
            set { this.deployedField = value; }
        }

        /// <remarks/>
        public bool started
        {
            get { return this.startedField; }
            set { this.startedField = value; }
        }

        /// <remarks/>
        public string state
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }

        /// <remarks/>
        public ProgressType progress
        {
            get { return this.progressField; }
            set { this.progressField = value; }
        }

        /// <remarks/>
        public VmwareToolsType vmwareTools
        {
            get { return this.vmwareToolsField; }
            set { this.vmwareToolsField = value; }
        }

        /// <remarks/>
        public VirtualHardwareType virtualHardware
        {
            get { return this.virtualHardwareField; }
            set { this.virtualHardwareField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datacenterId
        {
            get { return this.datacenterIdField; }
            set { this.datacenterIdField = value; }
        }

        /// <remarks/>
        public drsEligible drsEligible
        {
            get { return this.drsEligibleField; }
            set { this.drsEligibleField = value; }
        }

		/// <remarks/>
		public consistencyGroup consistencyGroup
	    {
			get { return this.consistencyGroupField; }
			set { this.consistencyGroupField = value; }
		}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class ServerTypeDisk
    {

        private string idField;

        private int scsiIdField;

        private int sizeGbField;

        private string speedField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int scsiId
        {
            get { return this.scsiIdField; }
            set { this.scsiIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int sizeGb
        {
            get { return this.sizeGbField; }
            set { this.sizeGbField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string speed
        {
            get { return this.speedField; }
            set { this.speedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class ServerTypeNetworkInfo
    {

        private NicType primaryNicField;

        private NicType[] additionalNicField;

        private string networkDomainIdField;

        /// <remarks/>
        public NicType primaryNic
        {
            get { return this.primaryNicField; }
            set { this.primaryNicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalNic")]
        public NicType[] additionalNic
        {
            get { return this.additionalNicField; }
            set { this.additionalNicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string networkDomainId
        {
            get { return this.networkDomainIdField; }
            set { this.networkDomainIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class ServerTypeNic
    {

        private string idField;

        private string privateIpv4Field;

        private string networkIdField;

        private string networkNameField;

        private string macAddressField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string privateIpv4
        {
            get { return this.privateIpv4Field; }
            set { this.privateIpv4Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string networkId
        {
            get { return this.networkIdField; }
            set { this.networkIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string networkName
        {
            get { return this.networkNameField; }
            set { this.networkNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string macAddress
        {
            get { return this.macAddressField; }
            set { this.macAddressField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class ServerTypeBackup
    {

        private string assetIdField;

        private string servicePlanField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assetId
        {
            get { return this.assetIdField; }
            set { this.assetIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string servicePlan
        {
            get { return this.servicePlanField; }
            set { this.servicePlanField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class ServerTypeMonitoring
    {

        private string monitoringIdField;

        private string servicePlanField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string monitoringId
        {
            get { return this.monitoringIdField; }
            set { this.monitoringIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string servicePlan
        {
            get { return this.servicePlanField; }
            set { this.servicePlanField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("servers", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class ServersResponseCollection
    {

        private ServerType[] serverField;

        private int pageNumberField;

        private bool pageNumberFieldSpecified;

        private int pageCountField;

        private bool pageCountFieldSpecified;

        private int totalCountField;

        private bool totalCountFieldSpecified;

        private int pageSizeField;

        private bool pageSizeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("server")]
        public ServerType[] Server
        {
            get { return this.serverField; }
            set { this.serverField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageNumber
        {
            get { return this.pageNumberField; }
            set { this.pageNumberField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified
        {
            get { return this.pageNumberFieldSpecified; }
            set { this.pageNumberFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageCount
        {
            get { return this.pageCountField; }
            set { this.pageCountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageCountSpecified
        {
            get { return this.pageCountFieldSpecified; }
            set { this.pageCountFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int totalCount
        {
            get { return this.totalCountField; }
            set { this.totalCountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified
        {
            get { return this.totalCountFieldSpecified; }
            set { this.totalCountFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageSize
        {
            get { return this.pageSizeField; }
            set { this.pageSizeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get { return this.pageSizeFieldSpecified; }
            set { this.pageSizeFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("deployServer", Namespace = "urn:didata.com:api:cloud:types",
        IsNullable = false)]
    public partial class DeployServerType
    {

        private string nameField;

        private string descriptionField;

        private string imageIdField;

        private bool startField;

        private string administratorPasswordField;

        private DeployServerTypeCpu cpuField;

        private uint memoryGbField;

        private bool memoryGbFieldSpecified;

        private object itemField;

        private string primaryDnsField;

        private string secondaryDnsField;

        private string ipv4GatewayField;

        private DeployServerTypeDisk[] diskField;

        private string microsoftTimeZoneField;

        /// <remarks/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <remarks/>
        public string imageId
        {
            get { return this.imageIdField; }
            set { this.imageIdField = value; }
        }

        /// <remarks/>
        public bool start
        {
            get { return this.startField; }
            set { this.startField = value; }
        }

        /// <remarks/>
        public string administratorPassword
        {
            get { return this.administratorPasswordField; }
            set { this.administratorPasswordField = value; }
        }

        /// <remarks/>
        public DeployServerTypeCpu cpu
        {
            get { return this.cpuField; }
            set { this.cpuField = value; }
        }

        /// <remarks/>
        public uint memoryGb
        {
            get { return this.memoryGbField; }
            set { this.memoryGbField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool memoryGbSpecified
        {
            get { return this.memoryGbFieldSpecified; }
            set { this.memoryGbFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("network", typeof (DeployServerTypeNetwork))]
        [System.Xml.Serialization.XmlElementAttribute("networkInfo", typeof (DeployServerTypeNetworkInfo))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        public string primaryDns
        {
            get { return this.primaryDnsField; }
            set { this.primaryDnsField = value; }
        }

        /// <remarks/>
        public string secondaryDns
        {
            get { return this.secondaryDnsField; }
            set { this.secondaryDnsField = value; }
        }
        
        /// <remarks/>
        public string ipv4Gateway
        {
            get { return this.ipv4GatewayField; }
            set { this.ipv4GatewayField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("disk")]
        public DeployServerTypeDisk[] disk
        {
            get { return this.diskField; }
            set { this.diskField = value; }
        }

        /// <remarks/>
        public string microsoftTimeZone
        {
            get { return this.microsoftTimeZoneField; }
            set { this.microsoftTimeZoneField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class DeployServerTypeCpu
    {

        private string speedField;

        private uint countField;

        private bool countFieldSpecified;

        private uint coresPerSocketField;

        private bool coresPerSocketFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string speed
        {
            get { return this.speedField; }
            set { this.speedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint count
        {
            get { return this.countField; }
            set { this.countField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified
        {
            get { return this.countFieldSpecified; }
            set { this.countFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint coresPerSocket
        {
            get { return this.coresPerSocketField; }
            set { this.coresPerSocketField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coresPerSocketSpecified
        {
            get { return this.coresPerSocketFieldSpecified; }
            set { this.coresPerSocketFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class DeployServerTypeNetwork
    {

        private string itemField;

        private NetworkIdOrPrivateIpv4ChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("networkId", typeof (string))]
        [System.Xml.Serialization.XmlElementAttribute("privateIpv4", typeof (string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public NetworkIdOrPrivateIpv4ChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types", IncludeInSchema = false)]
    public enum NetworkIdOrPrivateIpv4ChoiceType
    {

        /// <remarks/>
        networkId,

        /// <remarks/>
        privateIpv4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class DeployServerTypeNetworkInfo
    {

        private NewNicType primaryNicField;

        private NewNicType[] additionalNicField;

        private string networkDomainIdField;

        /// <remarks/>
        public NewNicType primaryNic
        {
            get { return this.primaryNicField; }
            set { this.primaryNicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalNic")]
        public NewNicType[] additionalNic
        {
            get { return this.additionalNicField; }
            set { this.additionalNicField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string networkDomainId
        {
            get { return this.networkDomainIdField; }
            set { this.networkDomainIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class DeployServerTypeDisk
    {

        private ushort scsiIdField;

        private string speedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort scsiId
        {
            get { return this.scsiIdField; }
            set { this.scsiIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string speed
        {
            get { return this.speedField; }
            set { this.speedField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("notifyNicIpChange", Namespace = "urn:didata.com:api:cloud:types",
        IsNullable = false)]
    public partial class NotifyNicIpChangeType
    {

        private string privateIpv4Field;

        private string ipv6Field;

        private string nicIdField;

        /// <remarks/>
        public string privateIpv4
        {
            get { return this.privateIpv4Field; }
            set { this.privateIpv4Field = value; }
        }

        /// <remarks/>
        public string ipv6
        {
            get { return this.ipv6Field; }
            set { this.ipv6Field = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nicId
        {
            get { return this.nicIdField; }
            set { this.nicIdField = value; }
        }
    }
	 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("addNic", Namespace = "urn:didata.com:api:cloud:types",
        IsNullable = false)]
    public partial class AddNicType
    {

        private string serverIdField;

        private VlanIdOrPrivateIpType nicField;

        /// <remarks/>
        public string serverId
        {
            get { return this.serverIdField; }
            set { this.serverIdField = value; }
        }

        /// <remarks/>
        public VlanIdOrPrivateIpType nic
        {
            get { return this.nicField; }
            set { this.nicField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("removeNic", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class RemoveNicType
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	A delete server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("deleteServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class DeleteServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	A start server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("startServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class StartServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	A shutdown server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("shutdownServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class ShutdownServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	A reboot server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("rebootServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class RebootServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	A reset server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("resetServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class ResetServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	A power off server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("powerOffServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class PowerOffServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	An update vmware tools server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("updateVmwareTools", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class UpdateVmwareToolsServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <content>	An update vmware tools server type. </content>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("upgradeVirtualHardware", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class UpgradeVirtualHardware
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("cleanServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class CleanServerType
    {
        private string idField;
        /// <summary>	Gets or sets the identifier of the server. </summary>
        /// <value>	The identifier of the server. </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("enableServerMonitoring", Namespace = "urn:didata.com:api:cloud:types",
        IsNullable = false)]
    public partial class EnableServerMonitoringType
    {

        private string servicePlanField;

        private string idField;

        /// <remarks/>
        public string servicePlan
        {
            get { return this.servicePlanField; }
            set { this.servicePlanField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("disableServerMonitoring", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class DisableServerMonitoringType
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
	
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("changeServerMonitoringPlan",
        Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class ChangeServerMonitoringPlanType
    {

        private string servicePlanField;

        private string idField;

        /// <remarks/>
        public string servicePlan
        {
            get { return this.servicePlanField; }
            set { this.servicePlanField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("addLocalDisk", Namespace = "urn:didata.com:api:cloud:types",
        IsNullable = false)]
    public partial class AddLocalDiskType
    {

        private int sizeGbField;

        private string speedField;

        private int scsiIdField;

        private bool scsiIdFieldSpecified;

        private string idField;

        /// <remarks/>
        public int sizeGb
        {
            get { return this.sizeGbField; }
            set { this.sizeGbField = value; }
        }

        /// <remarks/>
        public string speed
        {
            get { return this.speedField; }
            set { this.speedField = value; }
        }

        /// <remarks/>
        public int scsiId
        {
            get { return this.scsiIdField; }
            set { this.scsiIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scsiIdSpecified
        {
            get { return this.scsiIdFieldSpecified; }
            set { this.scsiIdFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("reconfigureServer", Namespace = "urn:didata.com:api:cloud:types",
        IsNullable = false)]
    public partial class ReconfigureServerType
    {

        private uint memoryGbField;

        private bool memoryGbFieldSpecified;

        private uint cpuCountField;

        private bool cpuCountFieldSpecified;

        private string cpuSpeedField;

        private uint coresPerSocketField;

        private bool coresPerSocketFieldSpecified;

        private string idField;

        /// <remarks/>
        public uint memoryGb
        {
            get { return this.memoryGbField; }
            set { this.memoryGbField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool memoryGbSpecified
        {
            get { return this.memoryGbFieldSpecified; }
            set { this.memoryGbFieldSpecified = value; }
        }

        /// <remarks/>
        public uint cpuCount
        {
            get { return this.cpuCountField; }
            set { this.cpuCountField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cpuCountSpecified
        {
            get { return this.cpuCountFieldSpecified; }
            set { this.cpuCountFieldSpecified = value; }
        }

        /// <remarks/>
        public string cpuSpeed
        {
            get { return this.cpuSpeedField; }
            set { this.cpuSpeedField = value; }
        }

        /// <remarks/>
        public uint coresPerSocket
        {
            get { return this.coresPerSocketField; }
            set { this.coresPerSocketField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coresPerSocketSpecified
        {
            get { return this.coresPerSocketFieldSpecified; }
            set { this.coresPerSocketFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("nic", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class NicWithSecurityGroupType
    {

        private string typeField;

        private string ipv4AddressField;

        private string ipv6AddressField;

        private string stateField;

        private string serverIdField;

        private string serverNameField;

        private string serverDescriptionField;

        private NicWithSecurityGroupTypeSecurityGroup securityGroupField;

        private string idField;

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string ipv4Address
        {
            get
            {
                return this.ipv4AddressField;
            }
            set
            {
                this.ipv4AddressField = value;
            }
        }

        /// <remarks/>
        public string ipv6Address
        {
            get
            {
                return this.ipv6AddressField;
            }
            set
            {
                this.ipv6AddressField = value;
            }
        }

        /// <remarks/>
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string serverId
        {
            get
            {
                return this.serverIdField;
            }
            set
            {
                this.serverIdField = value;
            }
        }

        /// <remarks/>
        public string serverName
        {
            get
            {
                return this.serverNameField;
            }
            set
            {
                this.serverNameField = value;
            }
        }

        /// <remarks/>
        public string serverDescription
        {
            get
            {
                return this.serverDescriptionField;
            }
            set
            {
                this.serverDescriptionField = value;
            }
        }

        /// <remarks/>
        public NicWithSecurityGroupTypeSecurityGroup securityGroup
        {
            get
            {
                return this.securityGroupField;
            }
            set
            {
                this.securityGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class NicWithSecurityGroupTypeSecurityGroup
    {

        private string nameField;

        private string descriptionField;

        private string stateField;

        private string idField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class nics
    {

        private NicWithSecurityGroupType[] nicField;

        private int pageNumberField;

        private bool pageNumberFieldSpecified;

        private int pageCountField;

        private bool pageCountFieldSpecified;

        private int totalCountField;

        private bool totalCountFieldSpecified;

        private int pageSizeField;

        private bool pageSizeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nic")]
        public NicWithSecurityGroupType[] nic
        {
            get
            {
                return this.nicField;
            }
            set
            {
                this.nicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNumberSpecified
        {
            get
            {
                return this.pageNumberFieldSpecified;
            }
            set
            {
                this.pageNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageCount
        {
            get
            {
                return this.pageCountField;
            }
            set
            {
                this.pageCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageCountSpecified
        {
            get
            {
                return this.pageCountFieldSpecified;
            }
            set
            {
                this.pageCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified
        {
            get
            {
                return this.totalCountFieldSpecified;
            }
            set
            {
                this.totalCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("addDisk", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class AddDiskType
    {

        /// <remarks/>
        public int sizeGb;

        /// <remarks/>
        public string speed;

        /// <remarks/>
        public int scsiId;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scsiIdSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("removeDisk", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class RemoveDiskType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("drsEligible", Namespace = "urn:didata.com:api:cloud:types")]
    public partial class drsEligible
    {
    }

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
	[System.Xml.Serialization.XmlRootAttribute("consistencyGroup", Namespace = "urn:didata.com:api:cloud:types")]
	public partial class consistencyGroup
	{
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string status;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string serverRole;
	}
}
