//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


namespace DD.CBU.Compute.Api.Contracts.Directory
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oec.api.opsource.net/schemas/directory")]
    [System.Xml.Serialization.XmlRootAttribute("Account", Namespace="http://oec.api.opsource.net/schemas/directory", IsNullable=false)]
    public partial class AccountType {
    
        private string userNameField;
    
        private string passwordField;
    
        private string fullNameField;
    
        private string firstNameField;
    
        private string lastNameField;
    
        private string emailAddressField;
    
        private string departmentField;
    
        private string customDefined1Field;
    
        private string customDefined2Field;
    
        private string orgIdField;
    
        private RoleType[] rolesField;
    
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
    
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    
        /// <remarks/>
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    
        /// <remarks/>
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
    
        /// <remarks/>
        public string customDefined1 {
            get {
                return this.customDefined1Field;
            }
            set {
                this.customDefined1Field = value;
            }
        }
    
        /// <remarks/>
        public string customDefined2 {
            get {
                return this.customDefined2Field;
            }
            set {
                this.customDefined2Field = value;
            }
        }
    
        /// <remarks/>
        public string orgId {
            get {
                return this.orgIdField;
            }
            set {
                this.orgIdField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("role", IsNullable=false)]
        public RoleType[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
    }
}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/network")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/network", IsNullable=false)]
//public partial class NetworkWithLocations {
    
//    private NetworkWithLocationType[] networkField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("network")]
//    public NetworkWithLocationType[] network {
//        get {
//            return this.networkField;
//        }
//        set {
//            this.networkField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false)]
//public partial class ServerImages {
    
//    private ServerImageType[] serverImageField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("ServerImage")]
//    public ServerImageType[] ServerImage {
//        get {
//            return this.serverImageField;
//        }
//        set {
//            this.serverImageField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false)]
//public partial class Servers {
    
//    private ServerType[] serverField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("Server")]
//    public ServerType[] Server {
//        get {
//            return this.serverField;
//        }
//        set {
//            this.serverField = value;
//        }
//    }
//}

// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false)]
//public partial class SoftwareLabels {
    
//    private SoftwareLabelType[] softwareLabelField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("softwareLabel")]
//    public SoftwareLabelType[] softwareLabel {
//        get {
//            return this.softwareLabelField;
//        }
//        set {
//            this.softwareLabelField = value;
//        }
//    }
//}