//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false)]
public partial class Servers {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ServersWithBackup")]
    public Server[] Items;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class Server {
    
    /// <remarks/>
    public string id;

    /// <summary/>
    public string location;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public string description;

    /// <summary/>
    public DeployedServersWithDisksDeployedServerWithDisksMachineSpecificationOperatingSystem operatingSystem;

    /// <remarks/>
    public string cpuCount;

    /// <remarks/>
    public string memoryMb;

    /// <remarks/>
    public Disk[] disk;

    /// <remarks/>
    public string sourceImageId;

    /// <remarks/>
    public string networkId;

    /// <remarks/>
    public string machineName;

    /// <remarks/>
    public string privateIp;

    /// <remarks/>
    public string created;

    /// <remarks/>
    public string isDeployed;

    /// <remarks/>
    public string isStarted;

    /// <remarks/>
    public string state;
    
    // <remarks/>
//    public string softwareLabel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("machineStatus")]
    public DeployedServersWithDisksDeployedServerWithDisksMachineStatus[] machineStatus;
 }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class DeployedServersWithDisksDeployedServerWithDisksMachineSpecification {
    
    /// <remarks/>
    public string cpuCount;
    
    /// <remarks/>
    public string memoryMb;
    
    /// <remarks/>
    public string osStorageGb;
    
    /// <remarks/>
    public string additionalLocalStorageGb;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("operatingSystem")]
    public DeployedServersWithDisksDeployedServerWithDisksMachineSpecificationOperatingSystem operatingSystem;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class DeployedServersWithDisksDeployedServerWithDisksMachineSpecificationOperatingSystem
{
    /// <summary/>
    public string id;

    /// <remarks/>
    public string type;
    
    /// <remarks/>
    public string displayName;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class DeployedServersWithDisksDeployedServerWithDisksMachineStatus {
    
    /// <remarks/>
    public string value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class Disk {
    
    /// <remarks/>
    public string id;
    
    /// <remarks/>
    public string scsiId;
    
    /// <remarks/>
    public string sizeGb;

    /// <summary/>
    public string speed;

    /// <remarks/>
    public string state;
}
