//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false)]
public partial class DeployedImagesWithSoftwareLabels {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeployedImageWithSoftwareLabels")]
    public DeployedImageWithSoftwareLabels[] Items;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class DeployedImageWithSoftwareLabels {
    
    /// <remarks/>
    public string id;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    public string deployedTime;
    
    /// <remarks/>
    public string location;
    
    /// <remarks/>
    public string softwareLabel;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("machineSpecification")]
    public DeployedImageWithSoftwareLabelsMachineSpecification machineSpecification;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class DeployedImageWithSoftwareLabelsMachineSpecification {
    
    /// <remarks/>
    public string cpuCount;
    
    /// <remarks/>
    public string memoryMb;
    
    /// <remarks/>
    public string osStorageGb;
    
    /// <remarks/>
    public string additionalLocalStorageGb;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("operatingSystem")]
    public DeployedImageWithSoftwareLabelsMachineSpecificationOperatingSystem operatingSystem;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class DeployedImageWithSoftwareLabelsMachineSpecificationOperatingSystem {
    
    /// <remarks/>
    public string type;
    
    /// <remarks/>
    public string displayName;
}
