//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false)]
//public partial class ServersWithBackup {
//    /// <remarks/>
//    [XmlElement("server")]
//    public ServersWithBackupServer[] Items { get; set; }

//    /// <remarks/>
//    [XmlAttribute()]
//    public string pageNumber { get; set; }

//    /// <remarks/>
//    [XmlAttribute()]
//    public string pageCount { get; set; }

//    /// <remarks/>
//    [XmlAttribute()]
//    public string totalCount { get; set; }

//    /// <remarks/>
//    [XmlAttribute()]
//    public string pageSize { get; set; }
//}

// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
//public partial class ServersWithBackupServer {
//    /// <remarks/>
//    public string name { get; set; }

//    /// <remarks/>
//    public string description { get; set; }

//    /// <remarks/>
//    public string cpuCount { get; set; }

//    /// <remarks/>
//    public string memoryMb { get; set; }

//    /// <remarks/>
//    public string sourceImageId { get; set; }

//    /// <remarks/>
//    public string networkId { get; set; }

//    /// <remarks/>
//    public string machineName { get; set; }

//    /// <remarks/>
//    public string privateIp { get; set; }

//    /// <remarks/>
//    public string created { get; set; }

//    /// <remarks/>
//    public string isDeployed { get; set; }

//    /// <remarks/>
//    public string isStarted { get; set; }

//    /// <remarks/>
//    public string state { get; set; }

//    /// <remarks/>
//    [XmlElement("operatingSystem")]
//    public ServersWithBackupServerOperatingSystem[] operatingSystem { get; set; }

//    /// <remarks/>
//    [XmlElement("disk")]
//    public ServersWithBackupServerDisk[] disk { get; set; }

//    /// <remarks/>
//    [XmlElement("machineStatus")]
//    public ServersWithBackupServerMachineStatus[] machineStatus { get; set; }

//    /// <remarks/>
//    [XmlAttribute()]
//    public string id { get; set; }

//    /// <remarks/>
//    [XmlAttribute()]
//    public string location { get; set; }
//}
using DD.CBU.Compute.Api.Contracts.Server;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class ServersWithBackupServerOperatingSystem {
    /// <remarks/>
    [XmlAttribute()]
    public string id { get; set; }

    /// <remarks/>
    [XmlAttribute()]
    public string displayName { get; set; }

    /// <remarks/>
    [XmlAttribute()]
    public string type { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class ServersWithBackupServerDisk {
    /// <remarks/>
    [XmlAttribute()]
    public string id { get; set; }

    /// <remarks/>
    [XmlAttribute()]
    public string scsiId { get; set; }

    /// <remarks/>
    [XmlAttribute()]
    public string sizeGb { get; set; }

    /// <remarks/>
    [XmlAttribute()]
    public string speed { get; set; }

    /// <remarks/>
    [XmlAttribute()]
    public string state { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class ServersWithBackupServerMachineStatus {
    /// <remarks/>
    public string value { get; set; }

    /// <remarks/>
    [XmlAttribute()]
    public string name { get; set; }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false)]
public partial class NewDataSet {
    /// <remarks/>
    [XmlElement("ServersWithBackup")]
    public ServersWithBackup[] Items { get; set; }
}
