//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.CBU.Compute.Api.Contracts.Drs
{
    using System.Xml.Serialization;
    using DD.CBU.Compute.Api.Contracts.Network20;

	/// 
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
	public partial class ConsistencyGroupSnapshotType
	{
		private string idField;
		private System.DateTime createTimeField;
		private int sizeKbField;
		/// 
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}
		/// 
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime createTime
		{
			get
			{
				return this.createTimeField;
			}
			set
			{
				this.createTimeField = value;
			}
		}
		/// 
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int sizeKb
		{
			get
			{
				return this.sizeKbField;
			}
			set
			{
				this.sizeKbField = value;
			}
		}
	}
	/// 
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
	public partial class consistencyGroupSnapshots
	{
		private ConsistencyGroupSnapshotType[] snapshotField;
		private int totalCountField;
		private double journalUsageGbField;
		private string protectionWindowField;
		private string predictedProtectionWindowField;
		/// 
		[System.Xml.Serialization.XmlElementAttribute("snapshot")]
		public ConsistencyGroupSnapshotType[] snapshot
		{
			get
			{
				return this.snapshotField;
			}
			set
			{
				this.snapshotField = value;
			}
		}
		/// 
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int totalCount
		{
			get
			{
				return this.totalCountField;
			}
			set
			{
				this.totalCountField = value;
			}
		}
		/// 
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public double journalUsageGb
		{
			get
			{
				return this.journalUsageGbField;
			}
			set
			{
				this.journalUsageGbField = value;
			}
		}
		/// 
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "duration")]
		public string protectionWindow
		{
			get
			{
				return this.protectionWindowField;
			}
			set
			{
				this.protectionWindowField = value;
			}
		}
		/// 
		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "duration")]
		public string predictedProtectionWindow
		{
			get
			{
				return this.predictedProtectionWindowField;
			}
			set
			{
				this.predictedProtectionWindowField = value;
			}
		}
	}
}
