//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
/// 
/// 
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://oec.api.opsource.net/schemas/server", IsNullable=false, ElementName="Server")]
public partial class OpSourceServer {
    
    /// <remarks/>
    public string id;
    
    /// <remarks/>
    public string name;
    
    /// <remarks/>
    public string description;
    
    /// <remarks/>
    public string vlanResourcePath;
    
    /// <remarks/>
    public string imageResourcePath;
    
    /// <remarks/>
    public string cpuCount;
    
    /// <remarks/>
    public string memory;
    
    /// <remarks/>
    public string osStorage;
    
    /// <remarks/>
    public string additionalLocalStorage;
    
    /// <remarks/>
    public string machineName;
    
    /// <remarks/>
    public string privateIPAddress;
    
    /// <remarks/>
    public string isDeployed;
    
    /// <remarks/>
    public string isStarted;
    
    /// <remarks/>
    public string created;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("operatingSystem")]
    public ServerOperatingSystem operatingSystem;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oec.api.opsource.net/schemas/server")]
public partial class ServerOperatingSystem {
    
    /// <remarks/>
    public string type;
    
    /// <remarks/>
    public string displayName;
}